# -*- coding: utf-8 -*-
"""metodos solid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aLzZmDJxYaTgZi_AQjRuSOXRc6ubDp-
"""

from pydantic import BaseModel, Field, HttpUrl
from typing import Optional, List
from datetime import datetime
from uuid import UUID, uuid4


class LowSalesDetail(BaseModel):
    monthly_revenue: float
    target_revenue: float
    revenue_growth_rate: float  # Percentage: -0.15 for -15%
    average_ticket_value: float
    churn_rate: float = Field(ge=0, le=1) # Between 0 and 1

ronaldo = LowSalesDetail(monthly_revenue = 1000,
                       target_revenue = 1100,
                       revenue_growth_rate = -0.10,
                       average_ticket_value = 100,
                       churn_rate = 0.7)

class GetLowSales:
  def __init__(self, LowSalesDetail):
    self.issues = LowSalesDetail

  def detect_issues(self):
    issue = []
    if self.issues.monthly_revenue < self.issues.target_revenue:
      issue.append(f"Less expected revenue")

    if self.issues.revenue_growth_rate < 0:
      issue.append(f"Decrement in revenue")

    if self.issues.average_ticket_value > 100:
      issue.append(f"Expensive ticket value")

    if self.issues.churn_rate > 0.2:
      issue.append(f"Low retention rate")
    return issue

class LowTrafficDetail(BaseModel):
    total_visitors: int
    conversion_rate: float
    customer_acquisition_cost: float
    primary_acquisition_channel: str = Field(..., example="Social Media")
    bounce_rate: Optional[float] = None

class GetLowTraffic:
     def __init__(self, LowTrafficDetail):
      self.issuestraffic = LowTrafficDetail

     def detect_issues(self):
      issuetraffic = []
      if self.issuestraffic.conversion_rate < 0.3:
        issuetraffic.append(f"Less expected conversion rate")

      if self.issuestraffic.customer_acquisition_cost > 100:
        issuetraffic.append(f"Expensive customer acquisition cost")

      if self.issuestraffic.bounce_rate is not None and self.issuestraffic.bounce_rate > 0.6:
        issuetraffic.append(f"Big bounce rate")

      if self.issuestraffic.total_visitors < 10:
        issuetraffic.append(f"Low visitors rate")
      return issuetraffic

messi = LowTrafficDetail(total_visitors = 100,
                         conversion_rate = 0.4,
                         customer_acquisition_cost = 110,
                         primary_acquisition_channel = "Social Media",
                         bounce_rate = 0.7)

class DiagxSession:
    def __init__(self, detectors: list):
        self.detectors = detectors

    def run_diagnosis(self) -> list[str]:
        all_issues = []
        for detector in self.detectors:
            all_issues.extend(detector.detect_issues())
        return all_issues

session = DiagxSession([
    GetLowSales(ronaldo),
    GetLowTraffic(messi),
    # el día que agregues un quinto, solo sumás una línea acá
])

resultado = session.run_diagnosis()
print(resultado)